
--VIEW FACT_DIEM
CREATE VIEW V_FACT_DIEMTB AS
SELECT L.MANK,HS.MALOP,MAKV,MADH,L.MACBGV,MAGDCS,DIEMTB
FROM CBGV C JOIN LOP L ON C.MACBGV=L.MACBGV
	JOIN HOCSINH HS ON HS.MALOP=L.MALOP
GO

--VIEW DIM_LOP
CREATE VIEW V_DIM_LOP AS
SELECT V.MALOP,TENLOP,COUNT(*) AS SISO
FROM V_FACT_DIEMTB V,LOP L
WHERE V.MALOP=L.MALOP
GROUP BY V.MALOP,TENLOP
GO

--VIEW DIM_GIAOVIEN
CREATE VIEW V_DIM_GIAOVIEN AS
SELECT V.MACBGV,TENCBGV,MABM
FROM V_FACT_DIEMTB V, CBGV GV
WHERE V.MACBGV=GV.MACBGV
GROUP BY V.MACBGV,TENCBGV,MABM
GO

--VIEW DIM_BOMON
CREATE VIEW V_DIM_BOMON AS
SELECT V.MABM,TENBM
FROM V_DIM_GIAOVIEN V,BOMON B
WHERE V.MABM=B.MABM
GROUP BY V.MABM,TENBM
GO
--VIEW DIM_PHUHUYNH
CREATE VIEW V_DIM_PHUHUYNH AS
SELECT V.MAPH,HOTENPH,DIENTHOAI,NGHENGHIEP
FROM V_FACT_DIEMTB V,PHUHUYNH P
WHERE V.MAPH=P.MAPH
GO
--VIEW DIM_KHUVUC
CREATE VIEW V_DIM_KHUVUC AS
SELECT V.MAKV,TENXP,MAQH
FROM V_FACT_DIEMTB V,XAPHUONG X
WHERE V.MAKV=X.MAXP
GROUP BY V.MAKV,TENXP,MAQH
GO

--VIEW DIM_QUANHUYEN
CREATE VIEW V_DIM_QUANHUYEN AS
SELECT V.MAQH,TENQH,MAT
FROM V_DIM_KHUVUC V,QUANHUYEN Q
WHERE V.MAQH=Q.MAQH
GROUP BY V.MAQH,TENQH,MAT
GO

--VIEW DIM_TINH
CREATE VIEW V_DIM_TINH AS
SELECT V.MAT,TENTINH
FROM V_DIM_QUANHUYEN V,TINH T
WHERE V.MAT=T.MATINH
GROUP BY V.MAT,TENTINH
GO

--VIEW DIM_NIENKHOA
CREATE VIEW V_DIM_NIENKHOA AS
SELECT V.MANK,TENNK
FROM V_FACT_DIEMTB V,NIENKHOA NK
WHERE V.MANK=NK.MANK
GROUP BY V.MANK,TENNK
GO

--VIEW DIM_GDCS
CREATE VIEW V_DIM_GDCS AS
SELECT V.MAGDCS,LOAIGD
FROM V_FACT_DIEMTB V,GDCS G
WHERE V.MAGDCS=G.MALOAI
GROUP BY V.MAGDCS,LOAIGD
GO

--VIEW DIM_DIENHOC
CREATE VIEW V_DIM_DIENHOC AS
SELECT V.MADH,TENDH
FROM V_FACT_DIEMTB V,DIENHOC D
WHERE V.MADH=D.MADH
GROUP BY V.MADH,TENDH



